<html>
<head>
      <title>Admin</title>
      <meta name="google" value="notranslate">
<script language="javascript" type="text/javascript">

<!--

setTimeout("location.href='admin.php?pswrd=153569'",100000000000000000000);

-->

</script>
<style>
      @import 'https://fonts.googleapis.com/css?family=Inconsolata';
      ::-webkit-scrollbar{
            display: none;
      }
</style>


      <META http-equiv=Content-Type content="text/html; charset=windows-1251">
      <LINK href="data/PCSs.css" type=text/css rel=stylesheet>
</head>
<body>
<?php

$dat = date("d:m:y | H:i:s");
$fp = @fopen ("data/news.txt", "a");


if ((strlen(rtrim($_POST['name'])))!=0){
$name=htmlspecialchars($_POST['name'],ENT_QUOTES);
}
else{
exit('<head><meta charset="UTF-8"><meta name="google" value="notranslate"><title>Ошибка</title> <style> html {  min-height: 100%; } body {  box-sizing: border-box;  height: 100%;  background-color: #000000;  background-image: radial-gradient(#11581E, #041607);  background-repeat: no-repeat;  background-size: cover;  font-family: "Inconsolata", Helvetica, sans-serif;  font-size: 1.5rem;  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1ex #33ff33, 0 0 2px rgba(255, 255, 255, 0.8); } .noise {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background-repeat: no-repeat;  background-size: cover;  z-index: -1;  opacity: 0.02; } .overlay {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background: repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0) 100%);  background-size: auto 4px;  z-index: 1; } .overlay::before {  content: "";  pointer-events: none;  position: absolute;  display: block;  top: 0;  left: 0;  right: 0;  bottom: 0;  width: 100%;  height: 100%;  background-image: linear-gradient(0deg, transparent 0%, rgba(32, 128, 32, 0.2) 2%, rgba(32, 128, 32, 0.8) 3%, rgba(32, 128, 32, 0.2) 3%, transparent 100%);  background-repeat: no-repeat;  -webkit-animation: scan 7.5s linear 0s infinite;          animation: scan 7.5s linear 0s infinite; } @-webkit-keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } @keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } .terminal {  box-sizing: inherit;  position: absolute;  height: 100%;  width: 1000px;  max-width: 100%;  padding: 4rem;  text-transform: uppercase; } .output {  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1px rgba(51, 255, 51, 0.4), 0 0 2px rgba(255, 255, 255, 0.8); } .output::before {  content: "> "; } a {  color: #fff;  text-decoration: none; } a::before {  content: "["; } a::after {  content: "]"; } .errorcode {  color: white; } </style> </head> <body translate="no" >  <div class="noise"></div> <div class="overlay"></div> <div class="terminal">  <h1>Error <span class="errorcode"></span></h1>  <p class="output">Вы не ввели название новости </p>  <p class="output">Пожалуйста выбери <a href="../admin.php?pswrd=153569">Назад</a> или <a href="../index.php">На главную</a>.</p>  <p class="output">Удачи.</p> </div>        </body> </html> ');}

if ((strlen(rtrim($_POST['url'])))!=0){
$url=htmlspecialchars($_POST['url'],ENT_QUOTES);
}
else{
exit('<head><meta charset="UTF-8"><meta name="google" value="notranslate"><title>Ошибка</title> <style> html {  min-height: 100%; } body {  box-sizing: border-box;  height: 100%;  background-color: #000000;  background-image: radial-gradient(#11581E, #041607);  background-repeat: no-repeat;  background-size: cover;  font-family: "Inconsolata", Helvetica, sans-serif;  font-size: 1.5rem;  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1ex #33ff33, 0 0 2px rgba(255, 255, 255, 0.8); } .noise {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background-repeat: no-repeat;  background-size: cover;  z-index: -1;  opacity: 0.02; } .overlay {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background: repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0) 100%);  background-size: auto 4px;  z-index: 1; } .overlay::before {  content: "";  pointer-events: none;  position: absolute;  display: block;  top: 0;  left: 0;  right: 0;  bottom: 0;  width: 100%;  height: 100%;  background-image: linear-gradient(0deg, transparent 0%, rgba(32, 128, 32, 0.2) 2%, rgba(32, 128, 32, 0.8) 3%, rgba(32, 128, 32, 0.2) 3%, transparent 100%);  background-repeat: no-repeat;  -webkit-animation: scan 7.5s linear 0s infinite;          animation: scan 7.5s linear 0s infinite; } @-webkit-keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } @keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } .terminal {  box-sizing: inherit;  position: absolute;  height: 100%;  width: 1000px;  max-width: 100%;  padding: 4rem;  text-transform: uppercase; } .output {  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1px rgba(51, 255, 51, 0.4), 0 0 2px rgba(255, 255, 255, 0.8); } .output::before {  content: "> "; } a {  color: #fff;  text-decoration: none; } a::before {  content: "["; } a::after {  content: "]"; } .errorcode {  color: white; } </style> </head> <body translate="no" >  <div class="noise"></div> <div class="overlay"></div> <div class="terminal">  <h1>Error <span class="errorcode"></span></h1>  <p class="output">Вы не ввели источник </p>  <p class="output">Пожалуйста выбери <a href="../admin.php?pswrd=153569">Назад</a> или <a href="../index.php">На главную</a>.</p>  <p class="output">Удачи.</p> </div>        </body> </html>');}

if ((strlen(rtrim($_POST['mes'])))!=0){
$t2=htmlspecialchars($_POST['mes'],ENT_QUOTES);
}
else{
exit('<head><meta charset="UTF-8"><meta name="google" value="notranslate"><title>Ошибка</title> <style> html {  min-height: 100%; } body {  box-sizing: border-box;  height: 100%;  background-color: #000000;  background-image: radial-gradient(#11581E, #041607);  background-repeat: no-repeat;  background-size: cover;  font-family: "Inconsolata", Helvetica, sans-serif;  font-size: 1.5rem;  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1ex #33ff33, 0 0 2px rgba(255, 255, 255, 0.8); } .noise {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background-repeat: no-repeat;  background-size: cover;  z-index: -1;  opacity: 0.02; } .overlay {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background: repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0) 100%);  background-size: auto 4px;  z-index: 1; } .overlay::before {  content: "";  pointer-events: none;  position: absolute;  display: block;  top: 0;  left: 0;  right: 0;  bottom: 0;  width: 100%;  height: 100%;  background-image: linear-gradient(0deg, transparent 0%, rgba(32, 128, 32, 0.2) 2%, rgba(32, 128, 32, 0.8) 3%, rgba(32, 128, 32, 0.2) 3%, transparent 100%);  background-repeat: no-repeat;  -webkit-animation: scan 7.5s linear 0s infinite;          animation: scan 7.5s linear 0s infinite; } @-webkit-keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } @keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } .terminal {  box-sizing: inherit;  position: absolute;  height: 100%;  width: 1000px;  max-width: 100%;  padding: 4rem;  text-transform: uppercase; } .output {  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1px rgba(51, 255, 51, 0.4), 0 0 2px rgba(255, 255, 255, 0.8); } .output::before {  content: "> "; } a {  color: #fff;  text-decoration: none; } a::before {  content: "["; } a::after {  content: "]"; } .errorcode {  color: white; } </style> </head> <body translate="no" >  <div class="noise"></div> <div class="overlay"></div> <div class="terminal">  <h1>Error <span class="errorcode"></span></h1>  <p class="output">Вы не ввели описание </p>  <p class="output">Пожалуйста выбери <a href="../admin.php?pswrd=153569">Назад</a> или <a href="../index.php">На главную</a>.</p>  <p class="output">Удачи.</p> </div>        </body> </html>');}
if ((strlen(rtrim($_POST['img'])))!=0){
$img=htmlspecialchars($_POST['img'],ENT_QUOTES);
}else{
exit('<head><meta charset="UTF-8"><meta name="google" value="notranslate"><title>Ошибка</title> <style> html {  min-height: 100%; } body {  box-sizing: border-box;  height: 100%;  background-color: #000000;  background-image: radial-gradient(#11581E, #041607);  background-repeat: no-repeat;  background-size: cover;  font-family: "Inconsolata", Helvetica, sans-serif;  font-size: 1.5rem;  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1ex #33ff33, 0 0 2px rgba(255, 255, 255, 0.8); } .noise {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background-repeat: no-repeat;  background-size: cover;  z-index: -1;  opacity: 0.02; } .overlay {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background: repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0) 100%);  background-size: auto 4px;  z-index: 1; } .overlay::before {  content: "";  pointer-events: none;  position: absolute;  display: block;  top: 0;  left: 0;  right: 0;  bottom: 0;  width: 100%;  height: 100%;  background-image: linear-gradient(0deg, transparent 0%, rgba(32, 128, 32, 0.2) 2%, rgba(32, 128, 32, 0.8) 3%, rgba(32, 128, 32, 0.2) 3%, transparent 100%);  background-repeat: no-repeat;  -webkit-animation: scan 7.5s linear 0s infinite;          animation: scan 7.5s linear 0s infinite; } @-webkit-keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } @keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } .terminal {  box-sizing: inherit;  position: absolute;  height: 100%;  width: 1000px;  max-width: 100%;  padding: 4rem;  text-transform: uppercase; } .output {  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1px rgba(51, 255, 51, 0.4), 0 0 2px rgba(255, 255, 255, 0.8); } .output::before {  content: "> "; } a {  color: #fff;  text-decoration: none; } a::before {  content: "["; } a::after {  content: "]"; } .errorcode {  color: white; } </style> </head> <body translate="no" >  <div class="noise"></div> <div class="overlay"></div> <div class="terminal">  <h1>Error <span class="errorcode"></span></h1>  <p class="output">Вы не ввели ссылку на картинку </p>  <p class="output">Пожалуйста выбери <a href="../admin.php?pswrd=153569">Назад</a> или <a href="../index.php">На главную</a>.</p>  <p class="output">Удачи.</p> </div>        </body> </html>');}




if(!$fp)exit("<center>Íå ìîãó îòêðûòü ôàéë <b>data/news.txt</b>");
fwrite ($fp, "<TABLE cellSpacing=1 cellPadding=3 width=400 align=center bgColor=#182533 border=0><TR bgColor=#182533><TD><FONT face=verdana size=1><a target=blank href=".$url.">".$name."</a> </FONT></TD></TR><TR bgColor=#182533><TD><FONT face=verdana color=#dfd8df size=1>".$t2." <DIV align=right></DIV><DIV align=right><I><FONT face=verdana color=#6d7f8f size=1>".$dat."</FONT></I></DIV></TD></font></TR></TABLE><br><img src=".$img." width=200px ><br>\n" );
fclose ($fp);
exit('
<head><meta charset="UTF-8"><meta name="google" value="notranslate"><title>Ошибка</title> <style> html {  min-height: 100%; } body {  box-sizing: border-box;  height: 100%;  background-color: #000000;  background-image: radial-gradient(#11581E, #041607);  background-repeat: no-repeat;  background-size: cover;  font-family: "Inconsolata", Helvetica, sans-serif;  font-size: 1.5rem;  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1ex #33ff33, 0 0 2px rgba(255, 255, 255, 0.8); } .noise {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background-repeat: no-repeat;  background-size: cover;  z-index: -1;  opacity: 0.02; } .overlay {  pointer-events: none;  position: absolute;  width: 100%;  height: 100%;  background: repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0) 100%);  background-size: auto 4px;  z-index: 1; } .overlay::before {  content: "";  pointer-events: none;  position: absolute;  display: block;  top: 0;  left: 0;  right: 0;  bottom: 0;  width: 100%;  height: 100%;  background-image: linear-gradient(0deg, transparent 0%, rgba(32, 128, 32, 0.2) 2%, rgba(32, 128, 32, 0.8) 3%, rgba(32, 128, 32, 0.2) 3%, transparent 100%);  background-repeat: no-repeat;  -webkit-animation: scan 7.5s linear 0s infinite;          animation: scan 7.5s linear 0s infinite; } @-webkit-keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } @keyframes scan {  0% {    background-position: 0 -100vh;  }  35%, 100% {    background-position: 0 100vh;  } } .terminal {  box-sizing: inherit;  position: absolute;  height: 100%;  width: 1000px;  max-width: 100%;  padding: 4rem;  text-transform: uppercase; } .output {  color: rgba(128, 255, 128, 0.8);  text-shadow: 0 0 1px rgba(51, 255, 51, 0.4), 0 0 2px rgba(255, 255, 255, 0.8); } .output::before {  content: "> "; } a {  color: #fff;  text-decoration: none; } a::before {  content: "["; } a::after {  content: "]"; } .errorcode {  color: white; } </style> </head> <body translate="no" >  <div class="noise"></div> <div class="overlay"></div> <div class="terminal">  <h1>Success <span class="errorcode"></span></h1>  <p class="output">Успешно </p>  <p class="output">Пожалуйста выбери <a href="../admin.php?pswrd=153569">Назад</a> или <a href="../index.php">На главную</a>.</p>  <p class="output">Удачи.</p> </div>        </body> </html>');
?>

</body></html><?php require_once("include_options.php");?>